name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.6
      
    - name: Navigate to workspace
      run: cd $GITHUB_WORKSPACE
     
    - name: Restore NuGet Packages
      run: nuget restore OpenFFBSharp.sln /p:Configuration=Release
      
    - name: Build
      run: msbuild OpenFFBSharp.sln
